server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: auth_user
    password: auth_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: my_super_secret_jwt_key_for_development_only_change_in_production_256bits
  expiration-ms: 1800000 # 30 minutes
  refresh-expiration-ms: 604800000 # 7 days

redis:
  host: localhost
  port: 6379
